namespace LuccaDevises.Utils;

using System.Collections.Generic;
using System.Linq;
using System.Collections.Immutable;
using LuccaDevises.Domain.Currency.Entities;

public static class IsoCurrencyResolver
{
    private static IList<IsoCurrency> IsoCurrencies = ImmutableList.Create(
        new IsoCurrency("AED", "UAE Dirham"),
        new IsoCurrency("AFN", "Afghani"),
        new IsoCurrency("ALL", "Lek"),
        new IsoCurrency("AMD", "Armenian Dram"),
        new IsoCurrency("ANG", "Netherlands Antillean Guilder"),
        new IsoCurrency("AOA", "Kwanza"),
        new IsoCurrency("ARS", "Argentine Peso"),
        new IsoCurrency("AUD", "Australian Dollar"),
        new IsoCurrency("AWG", "Aruban Florin"),
        new IsoCurrency("AZN", "Azerbaijan Manat"),
        new IsoCurrency("BAM", "Convertible Mark"),
        new IsoCurrency("BBD", "Barbados Dollar"),
        new IsoCurrency("BDT", "Taka"),
        new IsoCurrency("BGN", "Bulgarian Lev"),
        new IsoCurrency("BHD", "Bahraini Dinar"),
        new IsoCurrency("BIF", "Burundi Franc"),
        new IsoCurrency("BMD", "Bermudian Dollar"),
        new IsoCurrency("BND", "Brunei Dollar"),
        new IsoCurrency("BOB", "Boliviano"),
        new IsoCurrency("BOV", "Mvdol"),
        new IsoCurrency("BRL", "Brazilian Real"),
        new IsoCurrency("BSD", "Bahamian Dollar"),
        new IsoCurrency("BTN", "Ngultrum"),
        new IsoCurrency("BWP", "Pula"),
        new IsoCurrency("BYN", "Belarusian Ruble"),
        new IsoCurrency("BZD", "Belize Dollar"),
        new IsoCurrency("CAD", "Canadian Dollar"),
        new IsoCurrency("CDF", "Congolese Franc"),
        new IsoCurrency("CHE", "WIR Euro"),
        new IsoCurrency("CHF", "Swiss Franc"),
        new IsoCurrency("CHW", "WIR Franc"),
        new IsoCurrency("CLF", "Unidad de Fomento"),
        new IsoCurrency("CLP", "Chilean Peso"),
        new IsoCurrency("CNY", "Yuan Renminbi"),
        new IsoCurrency("COP", "Colombian Peso"),
        new IsoCurrency("COU", "Unidad de Valor Real"),
        new IsoCurrency("CRC", "Costa Rican Colon"),
        new IsoCurrency("CUC", "Peso Convertible"),
        new IsoCurrency("CUP", "Cuban Peso"),
        new IsoCurrency("CVE", "Cabo Verde Escudo"),
        new IsoCurrency("CZK", "Czech Koruna"),
        new IsoCurrency("DJF", "Djibouti Franc"),
        new IsoCurrency("DKK", "Danish Krone"),
        new IsoCurrency("DOP", "Dominican Peso"),
        new IsoCurrency("DZD", "Algerian Dinar"),
        new IsoCurrency("EGP", "Egyptian Pound"),
        new IsoCurrency("ERN", "Nakfa"),
        new IsoCurrency("ETB", "Ethiopian Birr"),
        new IsoCurrency("EUR", "Euro"),
        new IsoCurrency("FJD", "Fiji Dollar"),
        new IsoCurrency("FKP", "Falkland Islands Pound"),
        new IsoCurrency("GBP", "Pound Sterling"),
        new IsoCurrency("GEL", "Lari"),
        new IsoCurrency("GHS", "Ghana Cedi"),
        new IsoCurrency("GIP", "Gibraltar Pound"),
        new IsoCurrency("GMD", "Dalasi"),
        new IsoCurrency("GNF", "Guinean Franc"),
        new IsoCurrency("GTQ", "Quetzal"),
        new IsoCurrency("GYD", "Guyana Dollar"),
        new IsoCurrency("HKD", "Hong Kong Dollar"),
        new IsoCurrency("HNL", "Lempira"),
        new IsoCurrency("HRK", "Kuna"),
        new IsoCurrency("HTG", "Gourde"),
        new IsoCurrency("HUF", "Forint"),
        new IsoCurrency("IDR", "Rupiah"),
        new IsoCurrency("ILS", "New Israeli Sheqel"),
        new IsoCurrency("INR", "Indian Rupee"),
        new IsoCurrency("IQD", "Iraqi Dinar"),
        new IsoCurrency("IRR", "Iranian Rial"),
        new IsoCurrency("ISK", "Iceland Krona"),
        new IsoCurrency("JMD", "Jamaican Dollar"),
        new IsoCurrency("JOD", "Jordanian Dinar"),
        new IsoCurrency("JPY", "Yen"),
        new IsoCurrency("KES", "Kenyan Shilling"),
        new IsoCurrency("KGS", "Som"),
        new IsoCurrency("KHR", "Riel"),
        new IsoCurrency("KMF", "Comorian Franc "),
        new IsoCurrency("KPW", "North Korean Won"),
        new IsoCurrency("KRW", "Won"),
        new IsoCurrency("KWD", "Kuwaiti Dinar"),
        new IsoCurrency("KYD", "Cayman Islands Dollar"),
        new IsoCurrency("KZT", "Tenge"),
        new IsoCurrency("LAK", "Lao Kip"),
        new IsoCurrency("LBP", "Lebanese Pound"),
        new IsoCurrency("LKR", "Sri Lanka Rupee"),
        new IsoCurrency("LRD", "Liberian Dollar"),
        new IsoCurrency("LSL", "Loti"),
        new IsoCurrency("LYD", "Libyan Dinar"),
        new IsoCurrency("MAD", "Moroccan Dirham"),
        new IsoCurrency("MDL", "Moldovan Leu"),
        new IsoCurrency("MGA", "Malagasy Ariary"),
        new IsoCurrency("MKD", "Denar"),
        new IsoCurrency("MMK", "Kyat"),
        new IsoCurrency("MNT", "Tugrik"),
        new IsoCurrency("MOP", "Pataca"),
        new IsoCurrency("MRU", "Ouguiya"),
        new IsoCurrency("MUR", "Mauritius Rupee"),
        new IsoCurrency("MVR", "Rufiyaa"),
        new IsoCurrency("MWK", "Malawi Kwacha"),
        new IsoCurrency("MXN", "Mexican Peso"),
        new IsoCurrency("MXV", "Mexican Unidad de Inversion(UDI)"),
        new IsoCurrency("MYR", "Malaysian Ringgit"),
        new IsoCurrency("MZN", "Mozambique Metical"),
        new IsoCurrency("NAD", "Namibia Dollar"),
        new IsoCurrency("NGN", "Naira"),
        new IsoCurrency("NIO", "Cordoba Oro"),
        new IsoCurrency("NOK", "Norwegian Krone"),
        new IsoCurrency("NPR", "Nepalese Rupee"),
        new IsoCurrency("NZD", "New Zealand Dollar"),
        new IsoCurrency("OMR", "Rial Omani"),
        new IsoCurrency("PAB", "Balboa"),
        new IsoCurrency("PEN", "Sol"),
        new IsoCurrency("PGK", "Kina"),
        new IsoCurrency("PHP", "Philippine Peso"),
        new IsoCurrency("PKR", "Pakistan Rupee"),
        new IsoCurrency("PLN", "Zloty"),
        new IsoCurrency("PYG", "Guarani"),
        new IsoCurrency("QAR", "Qatari Rial"),
        new IsoCurrency("RON", "Romanian Leu"),
        new IsoCurrency("RSD", "Serbian Dinar"),
        new IsoCurrency("RUB", "Russian Ruble"),
        new IsoCurrency("RWF", "Rwanda Franc"),
        new IsoCurrency("SAR", "Saudi Riyal"),
        new IsoCurrency("SBD", "Solomon Islands Dollar"),
        new IsoCurrency("SCR", "Seychelles Rupee"),
        new IsoCurrency("SDG", "Sudanese Pound"),
        new IsoCurrency("SEK", "Swedish Krona"),
        new IsoCurrency("SGD", "Singapore Dollar"),
        new IsoCurrency("SHP", "Saint Helena Pound"),
        new IsoCurrency("SLE", "Leone"),
        new IsoCurrency("SLL", "Leone"),
        new IsoCurrency("SOS", "Somali Shilling"),
        new IsoCurrency("SRD", "Surinam Dollar"),
        new IsoCurrency("SSP", "South Sudanese Pound"),
        new IsoCurrency("STN", "Dobra"),
        new IsoCurrency("SVC", "El Salvador Colon"),
        new IsoCurrency("SYP", "Syrian Pound"),
        new IsoCurrency("SZL", "Lilangeni"),
        new IsoCurrency("THB", "Baht"),
        new IsoCurrency("TJS", "Somoni"),
        new IsoCurrency("TMT", "Turkmenistan New Manat"),
        new IsoCurrency("TND", "Tunisian Dinar"),
        new IsoCurrency("TOP", "Pa’anga"),
        new IsoCurrency("TRY", "Turkish Lira"),
        new IsoCurrency("TTD", "Trinidad and Tobago Dollar"),
        new IsoCurrency("TWD", "New Taiwan Dollar"),
        new IsoCurrency("TZS", "Tanzanian Shilling"),
        new IsoCurrency("UAH", "Hryvnia"),
        new IsoCurrency("UGX", "Uganda Shilling"),
        new IsoCurrency("USD", "US Dollar"),
        new IsoCurrency("USN", "US Dollar(Next day)"),
        new IsoCurrency("UYI", "Uruguay Peso en Unidades Indexadas(UI)"),
        new IsoCurrency("UYU", "Peso Uruguayo"),
        new IsoCurrency("UYW", "Unidad Previsional"),
        new IsoCurrency("UZS", "Uzbekistan Sum"),
        new IsoCurrency("VED", "Bolívar Soberano"),
        new IsoCurrency("VES", "Bolívar Soberano"),
        new IsoCurrency("VND", "Dong"),
        new IsoCurrency("VUV", "Vatu"),
        new IsoCurrency("WST", "Tala"),
        new IsoCurrency("XAF", "CFA Franc BEAC"),
        new IsoCurrency("XAG", "Silver"),
        new IsoCurrency("XAU", "Gold"),
        new IsoCurrency("XBA", "Bond Markets Unit European Composite Unit(EURCO)"),
        new IsoCurrency("XBB", "Bond Markets Unit European Monetary Unit(E.M.U.- 6)"),
        new IsoCurrency("XBC", "Bond Markets Unit European Unit of Account 9(E.U.A.- 9)"),
        new IsoCurrency("XBD", "Bond Markets Unit European Unit of Account 17(E.U.A.- 17)"),
        new IsoCurrency("XCD", "East Caribbean Dollar"),
        new IsoCurrency("XDR", "SDR(Special Drawing Right)"),
        new IsoCurrency("XOF", "CFA Franc BCEAO"),
        new IsoCurrency("XPD", "Palladium"),
        new IsoCurrency("XPF", "CFP Franc"),
        new IsoCurrency("XPT", "Platinum"),
        new IsoCurrency("XSU", "Sucre"),
        new IsoCurrency("XTS", "Codes specifically reserved for testing purposes"),
        new IsoCurrency("XUA", "ADB Unit of Account"),
        new IsoCurrency("XXX", "The codes assigned for transactions where no currency is involved"),
        new IsoCurrency("YER", "Yemeni Rial"),
        new IsoCurrency("ZAR", "Rand"),
        new IsoCurrency("ZMW", "Zambian Kwacha"),
        new IsoCurrency("ZWL", "Zimbabwe Dollar")
    );

    public static IsoCurrency? GetIsoCurrency(string code)
    {
        return IsoCurrencies.FirstOrDefault(currency => currency.Code.Equals(code));
    }

}